name: Development CI

on:
  pull_request:
  workflow_dispatch:
  
jobs:
  test-agroio:
    name: Build and Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      # Required since some dependencies from private repos
      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Build C++ project and run C++ tests
        run: |
          mkdir build && cd build
          cmake -DRAILCAM_BUILD_TESTS=ON .. && cmake --build .
          ctest .
          cd ..