name: Production CI/CD

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  bump_version_and_tag:
    runs-on: ubuntu-latest
    name: "Bump version and create changelog with commitizen"
    permissions:
      contents: write
      id-token: write
    outputs:
      new_commit_sha: ${{ steps.push_changes.outputs.commit_sha }}
      version: ${{ steps.cz.outputs.version }}
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ github.token }}

      - name: Create bump and changelog
        id: cz
        uses: commitizen-tools/commitizen-action@master
        with:
          github_token: ${{ github.token }}
          changelog: false

      - name: Push changes and set new commit SHA
        id: push_changes
        run: |
          git push origin master --follow-tags
          echo "commit_sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

      - name: Print Version
        run: echo "Bumped to version ${{ steps.cz.outputs.version }}"