# cameras_ids.yaml
# Config file specific for every Scanner. Store the cameras IDs of the Scanner. Is called in multi_camera_node.launch.

camera_qty: 0
guid_0: "DEV_XXXXXXXXXXXX"
guid_1: "DEV_XXXXXXXXXXXX"
guid_2: "DEV_XXXXXXXXXXXX"
guid_3: "DEV_XXXXXXXXXXXX"
guid_4: "DEV_XXXXXXXXXXXX"
guid_5: "DEV_XXXXXXXXXXXX"
guid_6: "DEV_XXXXXXXXXXXX"